title: <p align="center"> Shruthi Annappa </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/shruthiannappa">GitHub</a>
  
  <br>   
  I'm working on Machine Learning from past 4years with overall 11 years of experience.
  <br>
  </p>



theme: jekyll-theme-minimal
