title: Shruthi Annappa
logo: /assets/img/logo.png
<a href="https://github.com/shruthiannappa">GitHub</a>
<p>
<br>   
  I am currently working as a Machine Learning Developer at SAP Labs
  I have overall 11 years of development experience
<br>
</p>

theme: jekyll-theme-minimal
