title: <p align="center"> Shruthi Annappa </p>
logo: /assets/img/logo.png

description:
  <p align="center">

  <a href="https://github.com/shruthiannappa">GitHub</a>
  
  <br>   
  I am working as a Machine learning developer from past 4 years at SAP Labs India Pvt Ltd. I have overall 11 years development experience.
  <br>
  </p>



theme: jekyll-theme-minimal
